### ISSUE TITLE
Doesn't enter in moodle by the hyperlink (with brand new user)

### ISSUE THREAD

**Issue by michelpm1** [frumbert/wp2moodle--wordpress-#11]
Hello, i want to thank you, this plugin is a awesome.
but, humm i have a little problem and if you can give me a glue  I will appreciate it ! =D

When i click in the hyperlink, after creating the user in wordpress, it redirects me to a blank page, if i click refresh, then i m redirected to moodle main page with the user logged in, strange or not , it happens only in the first time, after that, i can click in the link and is redirect right and automatic, i dont know why it happens only in the first time after the user is created, if u have a few minutes here is the link to the registration in my blog the email validation is disabled to make easer to create.

http://web-cursos.net.br/registre-se/

link to the login page in wordpress

http://web-cursos.net.br/my-account/

And here is the link to the product with the hyperlink to moodle

http://web-cursos.net.br/produto/programacao-orientada-a-objetos-com-java-basico-3/

the blank page:

![captura de tela 2015-04-28 as 15 41 02](https://cloud.githubusercontent.com/assets/4390192/7377489/0de11dee-edbd-11e4-9954-9cd439d61da5.png)

**Comment by michelpm1** [comment]
// redirect to the homepage
header( "Location: http://web-cursos.net.br/curso/index.php" );
//redirect($SESSION->wantsurl);

i tried to change your redirect to this but without success the problem still continue with a new account

**Comment by frumbert** [comment]
Ok I haven't yet had time to check this out with the latest releases, so perhaps something minor has changed in the process. I'll see what I can find out. Thanks for your input so far.

**Comment by michelpm1** [comment]
Ok, thanks!

**Comment by actXc** [comment]
@frumbert I have a demo installation with the latest release of WP, moodle and I had to do some change in the wp2moodle-moodle plugin to make it work.

@michelpm1 you could give my fork a try and report if this changes your problem:
I sent a pull request from: https://github.com/actXc/wp2moodle-moodle  
My demo page is working and uses two demo shop/membership plugins in parallel: WooCommerce/PMPro and digistore24/digimember.

But my server is still on debian squeeze, I can not tell if the same would happen on a new debian also.
https://github.com/actXc/wp2moodle-moodle/commit/43dfb730da6932b0bb5070342f93cc243f2b547a

**Comment by michelpm1** [comment]
Nice, thanks @actXc!, i will try soon as possible and than i give u guys a anwser.

**Comment by michelpm1** [comment]
I tried, but still the same problem, but i saw now i have moodle ver 2.6.1 installed i will try to update to 2.7.7 and see what happens.

**Comment by michelpm1** [comment]
I Found the problem i dont know why but version 2.6.1 was with that bug, now i upgraded my moodle to 2.8.5 and the plugin is working ! no more problem for the first time using the hyperlink !!
