### ISSUE TITLE
Suggestion/Request

### ISSUE THREAD

**Issue by phillies0179** [frumbert/wp2moodle--wordpress-#13]
Have you thought, or would you consider, an integration with CiviCRM? We use it for our constituent management and it works well, including capturing event payments. I think that the tie would be easy as the short code could be put in the civicrm event, but I am not 100% confident.

**Comment by frumbert** [comment]
This should work out of the box with any system that can show a page that can host the shortcode. I don't know the product you're speaking of but it says it can be deployed with wordpress.
