### ISSUE TITLE
Syntax error when activating plugin

### ISSUE THREAD

**Issue by Jornv** [frumbert/wp2moodle--wordpress-#16]
Hi,

I just tried to install your plugin and keep getting the following syntax error when I try to activate the plugin:
Parse error: syntax error, unexpected '[' in /var/www/vhosts/starterstraining.nl/httpdocs/newsite_2015/wp-content/plugins/wp2moodle/wp2m.php on line 185

Using wordpress verion 4.2.4. Would really appreciate if you could help out.

**Comment by frumbert** [comment]
What can you tell me about the server environment? Seems like a strange line to get that error on. Which branch did you download, or when (I just pull a merge yesterday)

**Comment by frumbert** [comment]
Try grabbing https://raw.githubusercontent.com/frumbert/wp2moodle--wordpress-/master/wp2m.php again and see if that helps.
