### ISSUE TITLE
don't work

### ISSUE THREAD

**Issue by pacogarciap** [frumbert/wp2moodle--wordpress-#17]
when click at menu wp2moodle send to 404 page...

**Comment by frumbert** [comment]
Closing issue, since you haven't reported anything.

**Comment by pacogarciap** [comment]
because don't do anything... what can report?

**Comment by frumbert** [comment]
use the "attach files" hint as seen below the reply box to attach a screenshot, debug log, or any other relevant detail. Then I can start to help.
