### ISSUE TITLE
Custom fields into Moodle

### ISSUE THREAD

**Issue by jb-fol** [frumbert/wp2moodle--wordpress-#18]
Thanks for all your work on this plugin - really appreciated.

With a bit of hacking on both the wp2m-moodle and wp2m-wordpress plugins, I've managed to push additional information from Wordpress to Moodle, eg. city, institution, department and phone1.

Could it be possible to push data to Moodle custom profile fields though?

**Comment by frumbert** [comment]
This *should* be possible, but you're going to have to write the data insertion and validation yourself I think. Take a look into `/user/profile/lib.php`, particularly the function `edit_save_data` and you'll see that it's doing a few thinks like a capability check on the user, and so on. Having a map of wordpress fields to moodle custom fields and all the validation that goes with it (not to mention changes to the schema either end) is a bit of a stretch for the plugin (well, for me).
