### ISSUE TITLE
Page keeps loading when I open the post.

### ISSUE THREAD

**Issue by mikeross6233m** [frumbert/wp2moodle--wordpress-#19]
I checked the server logs and I got this

[Sun Nov 29 15:50:07.563115 2015] [:error] [pid 15351] [client 127.0.0.1:57276] core\event\user_loggedin Object\n(\n [data:protected] => Array\n (\n [eventname] => \core\event\user_loggedin\n [component] => core\n [action] => loggedin\n [target] => user\n [objecttable] => user\n [objectid] => 2\n [crud] => r\n [edulevel] => 0\n [contextid] => 1\n [contextlevel] => 10\n [contextinstanceid] => 0\n [userid] => 2\n [courseid] => 0\n [relateduserid] => \n [anonymous] => 0\n [other] => Array\n (\n [username] => admin\n )\n\n [timecreated] => 1448792407\n )\n\n [logextra:protected] => \n [context:protected] => context_system Object\n (\n [_id:protected] => 1\n [_contextlevel:protected] => 10\n [_instanceid:protected] => 0\n [_path:protected] => /1\n [_depth:protected] => 1\n )\n\n [triggered:core\event\base:private] => 1\n [dispatched:core\event\base:private] => \n [restored:core\event\base:private] => \n [recordsnapshots:core\event\base:private] => Array\n (\n )\n\n)\n, referer: http://localhost/moodle/?
[Sun Nov 29 15:50:07.563231 2015] [:error] [pid 15351] [client 127.0.0.1:57276] 2, referer: http://localhost/moodle/?
[Sun Nov 29 16:01:24.806120 2015] [:error] [pid 17934] [client 127.0.0.1:57480] PHP Fatal error: Call to undefined function mcrypt_get_iv_size() in /var/www/html/wordpress2/wp-content/plugins/wp2moodle/wp2m.php on line 120, referer: http://localhost/wordpress2/?page_id=7

**Comment by frumbert** [comment]
You need to install the mcrypt php plugin before this will work (mcrypt is the library that does the encryption, so it needs to be present in both wordpress and moodle). I've put in a warning on the settings page if it's not found.

**Comment by mikeross6233m** [comment]
It worked after installing the mcrypt

Thanks
