### ISSUE TITLE
Shortcodes affecting post

### ISSUE THREAD

**Issue by hunterdt** [frumbert/wp2moodle--wordpress-#2]
Hi, 
I'm not sure if something else is interacting on my page in a weird way, but when I create a page and use the short codes, the only thing that shows is the page title. The content gets stripped out and the wordpress admin bar does not display. This also only happens when I'm logged in. When I'm not logged in, the text still appears and the short coded text is not a hyperlink (so it is working fine when not logged in).

Any suggestions on what I should look through or is there anything I could share with you to help find out what the problem is? Thanks so much for writing this. It is exactly what I need, so I'm looking forward to getting it set up. 

Here is the page I've been testing the shortcode on: http://www.zombiebased.com/forum-2/ 
The "Click" at the end of the first paragraph is what I put in the short code.

**Comment by frumbert** [comment]
Haven't been able to replicate problem in Moodle 2.8 and Wordpress 4.1 (both latest). Closing issue.
