### ISSUE TITLE
Course attribute not working

### ISSUE THREAD

**Issue by mediaformat** [frumbert/wp2moodle--wordpress-#35]
I can't seem to connect using the `course` attribute either, I've tried using a Moodle `course-id` as well as numeric `course id`, and `course shortname` to no avail.

Adding to my confusion is the example at wp2moodle.coursesuite.ninja 
where shortcode [ wp2moodle course=”course3″ ] links to course id 5.

Thanks

> Using latest versions of wp2moodle
> WP 4.7.4
> Moodle 3.2.2 (Build: 20170313)

**Comment by frumbert** [comment]
The identifier to use is not the numerical id of the course nor is it the shortname. The course id you're seeing in the demo could be any number and you may not know it at the wordpress end.

![edit_course_settings](https://cloud.githubusercontent.com/assets/592257/25725316/c5fa7296-3162-11e7-82d8-02e7eb91f0da.jpg)

**Comment by mediaformat** [comment]
My bad, I totally missed that field.
(the number part of the name with the fact that it takes alphanumeric characters threw me off).

Cheers
