### ISSUE TITLE
Open an Activity doesn't work

### ISSUE THREAD

**Issue by duennerd** [frumbert/wp2moodle--wordpress-#39]
Hi there

I'm using your plugin but I have some issue using the activity selector. 
I already wrote you about the activity selector. It is a little buggy and I'm not able to make it running. 

I updated on the latest wordpress (4.8.1) and moodle (3.3+ (Build: 20170629)) versions.
May it be possible that the plugin isn't compatible with these two versions?
Or are there other suggestions, why the activity selector isn't working?
Everything in the course is set visible, but I have several sections. 
The activities are distributed in these sections. 
Could this be the problem?

Thanks for you help. 

Greetings Daniel

**Comment by frumbert** [comment]
Hi there

Sorry for the delay. I have pushed a change up to github which changes the way activity ordering works in the plugin, and tested it with my wp 4.8.1 and moodle 3.3

go to https://github.com/frumbert/wp2moodle-moodle <https://github.com/frumbert/wp2moodle-moodle> grab the moodle end plugin and re-apply it to your site then see if this helps the activity ordering problem.

Cheers,
Tim

**Comment by duennerd** [comment]
Dear Team

It's working now. Thank you a lot. 

Greetings Daniel
