### ISSUE TITLE
Wp2moodle-moodle back to WP 

### ISSUE THREAD

**Issue by wakelamp** [frumbert/wp2moodle--wordpress-#4]
Hi,
Thank-you for your excellent plugins. 
Any ideas on a good way to allow Moodle learners to become WP users? Should we LDAP from moodle to WP ?
AND
What is a good way to watch for errors on the WP2moodle process?

Our steps are 
1. Create Customer in WP
2. WP2moodle
3. Customer bulk uploads learners in Moodle 
4. A learner decides to buy a course in WP but their user id doesn't exist, so they create a new one 
5. Wp2 moodle 

rgds Paul

**Comment by frumbert** [comment]
The typical usage pattern for this plugin is that a user self-registers inside Wordpress, and then a link hands them over to Moodle (creating them in Moodle, if required). It's a single-user each time.

If you need to go the other way, that's certainly tricker. You'll have to create a connector somewhere (if it's from Wordpress, you would use one of the Moodle webservices; if it's in Moodle you could create a local plugin and push the data back during the cron job, for instance).
