### ISSUE TITLE
Update the plugin?

### ISSUE THREAD

**Issue by sfauset** [frumbert/wp2moodle--wordpress-#43]
Does anyone have plans to update this plugin?

It throws errors with the latest version of moodle...

**Comment by elsimio** [comment]
would be great to migrate the plugin to use a settings.php file

**Comment by frumbert** [comment]
Last tested with Moodle 3.7.1+ (Build: 20190725), WordPress 5.2.2, PHP 7.1 - yes, if you have debugging on you get warnings but the functionality still works.
