### ISSUE TITLE
No-firstname No-lastname

### ISSUE THREAD

**Issue by ikito** [frumbert/wp2moodle--wordpress-#7]
All installed and working ok, No firstname or lastname is sent to Moodle. saved as: No-firstname and No-lastname. Array at wp2moodle_generate_hyperlink function is wrong.

must be:
"firstname" => $user->first_name,		// first name
"lastname" => $user->last_name,			// last name

**Comment by frumbert** [comment]
According to http://codex.wordpress.org/Function_Reference/get_currentuserinfo, it's `$current_user->user_firstname`. `first_name` is the name of the database field.

**Comment by frumbert** [comment]
According to http://codex.wordpress.org/Function_Reference/get_currentuserinfo, it's `$current_user->user_firstname`. `first_name` is the name of the database field.
